# -*- coding: utf-8 -*-
"""Correlation_and_Regression_Lines_A_Quick_Recap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rfiSKSq2xoup1PknZ-Y7vBLm8_W7Cmh
"""

import math

line1 = "Physics Scores  15  12  8   8   7   7   7   6   5   3"
line2 = "History Scores  10  25  17  11  13  17  20  13  9   15"

x = [int(e) for e in line1.split()[2:]]
y = [int(e) for e in line2.split()[2:]]

n = len(x)
ex = sum(x)/n
ey = sum(y)/n
numerator = sum([(xi - ex) * (yi - ey) for xi, yi in zip(x, y)])
denominator = math.sqrt(sum((xi - ex)**2 for xi in x) * sum((yi - ey)**2 for yi in y))
corr = numerator / denominator
print(f"{corr:.3f}")