# -*- coding: utf-8 -*-
"""Multiple_Linear_Regression_Predicting_House_Prices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBz51UHIP42h0hfDgFOxzuLTZPxwBYDz
"""

# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
from sklearn.linear_model import Lasso


f, n = map(int, input().split())

X_train = np.empty((n, f))
y_train = np.empty(n)

# Read the training data
for i in range(n):
    row = list(map(float, input().split()))
    X_train[i] = row[:f]
    y_train[i] = row[-1]

t = int(input())

X_test = np.empty((t, f))

# Read the testing data
for i in range(t):
    X_test[i] = list(map(float, input().split()))

lasso_model = Lasso(alpha=0.02)
lasso_model.fit(X_train, y_train)


# Predict on the test data
y_pred = lasso_model.predict(X_test)

for val in y_pred:
    print("{:.2f}".format(val))
y_pred = lasso_model.predict(X_test)

for val in y_pred:
    print("{:.2f\}".format(val))
$0